cabal-version:      3.4
name:               control-events
version:            0.1.0.0
synopsis:           Events for system control and monitoring
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Rodrigo Mesquita
maintainer:         rodrigo.m.mesquita@gmail.com
copyright:          Copyright (C) 2026 Rodrigo Mesquita
category:           Control
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  Control.Events
    build-depends:    base, bytestring, text, containers, async,
                      network-uri, uuid, aeson, net-mqtt
    hs-source-dirs:   src
    default-language: GHC2024

executable control-events
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base,
        control-events

    hs-source-dirs:   app
    default-language: GHC2024
