cabal-version:      3.4
name:               control-events
version:            0.1.0.0
synopsis:           Events for system control and monitoring
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Rodrigo Mesquita
maintainer:         rodrigo.m.mesquita@gmail.com
copyright:          Copyright (C) 2026 Rodrigo Mesquita
category:           Control
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  Control.Events, Control.Events.Health
    build-depends:    base, bytestring, text, containers, async,
                      network-uri, uuid, aeson, time, microlens, net-mqtt
    hs-source-dirs:   src
    default-language: GHC2024

library servant
    visibility: public
    exposed-modules:  Control.Events.Servant
    build-depends:    base, servant-server, control-events, net-mqtt, aeson
    hs-source-dirs:   servant
    default-extensions: LambdaCase
    default-language: GHC2021

executable control-events
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base,
        control-events,
        process,
        net-mqtt,
        optparse-applicative,
        time,
        text

    ghc-options: -threaded
    hs-source-dirs:   app
    default-extensions: LambdaCase, OverloadedRecordDot
    default-language: GHC2021
